# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e53d02bbe40c5d0d4e25a81241e41b278fc8041c13960911d52fa0f4623755b24459d2d4e092329eae6e17879b7dce5f35674bc7dc666ae45c5b0c4fc12b22dd

test:
  secret_key_base: f9a6fff9bb5de380980f16ba6f647537e48d3f7a6c8a6479c5bac0bb9c3cd6f77b5d17f28b4e4be632323eecf0908b472f64dd8d2cb3dc9a094d66a9fc9c5718

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
